apiVersion: v1
kind: Namespace
metadata:
  name: teamcluster
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "kubernetes.azure.com/scalesetpriority", "Operator": "Equal", "Value": "spot", "Effect": "NoSchedule"}]'
    scheduler.alpha.kubernetes.io/node-selector: "agentpool=nodes"
    